# Generated by Django 3.1.3 on 2020-12-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_studentenroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sclname', models.CharField(max_length=30)),
                ('scladdress', models.CharField(max_length=10)),
                ('scltown', models.CharField(max_length=40)),
                ('sclcontact', models.CharField(max_length=12)),
                ('sclemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
