# Generated by Django 3.1.3 on 2020-12-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_schoolenroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictationaudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_number', models.IntegerField()),
                ('audio_name', models.CharField(max_length=100)),
                ('audio_level', models.CharField(max_length=500)),
                ('audio_lang', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='audio')),
                ('audio_show', models.BooleanField()),
            ],
        ),
    ]
