# Generated by Django 3.1.3 on 2020-12-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_dictationaudio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictationaudio',
            old_name='audio_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dictationaudio',
            old_name='audio_file',
            new_name='path',
        ),
    ]
