# Generated by Django 3.1.3 on 2020-12-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_auto_20201226_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenroll',
            name='stu_isactive',
            field=models.BooleanField(default=True),
        ),
    ]
