# Generated by Django 3.1.3 on 2020-12-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_auto_20201228_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenroll',
            name='stusubject',
            field=models.CharField(default='Telugu', max_length=30),
        ),
    ]
