# Generated by Django 3.1.3 on 2021-01-02 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0012_auto_20201230_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('datenow', models.DateTimeField(auto_now=True)),
                ('examconducted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.studentenroll')),
            ],
        ),
    ]
