# Generated by Django 3.1.3 on 2021-01-02 13:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0013_studentexamstats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentExamStats',
            new_name='StudentTestStats',
        ),
    ]
