# Generated by Django 3.1.3 on 2021-01-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0014_auto_20210102_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteststats',
            name='testtype',
            field=models.CharField(default='PRE TEST', max_length=10),
        ),
    ]
