# Generated by Django 3.1.3 on 2021-01-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0015_studentteststats_testtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteststats',
            name='timegap',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='studentteststats',
            name='times',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
