# Generated by Django 3.1.3 on 2021-01-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0016_auto_20210102_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentteststats',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
