# Generated by Django 3.1.3 on 2021-01-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0018_auto_20210102_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='testschedule',
            name='test_type',
            field=models.CharField(default='PRE Test', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentteststats',
            name='datenow',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
