# Generated by Django 3.1.3 on 2021-01-04 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0019_auto_20210104_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentteststats',
            name='examconducted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentteststats',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.studentenroll'),
        ),
    ]
