# Generated by Django 3.1.3 on 2021-01-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0020_auto_20210105_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentteststats',
            name='testtype',
            field=models.CharField(max_length=10),
        ),
    ]
