# Generated by Django 3.1.3 on 2021-01-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0021_auto_20210105_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testschedule',
            name='showthis',
        ),
        migrations.AddField(
            model_name='testschedule',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
