# Generated by Django 3.1.3 on 2021-01-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0022_auto_20210106_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='testschedule',
            name='test_level',
            field=models.CharField(default='Sunnapadaalu', max_length=20),
        ),
    ]
