# Generated by Django 3.1.3 on 2021-01-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0024_telugulevels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telugulevels',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='telugulevels',
            name='nickname',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='telugulevels',
            name='shortname',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
