# Generated by Django 3.1.3 on 2021-01-06 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0025_auto_20210106_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStudeentStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datenow', models.DateTimeField(auto_now_add=True)),
                ('timegap', models.CharField(default='-', max_length=2)),
                ('times', models.CharField(default='-', max_length=2)),
                ('examconducted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.studentenroll')),
            ],
        ),
        migrations.AlterField(
            model_name='testschedule',
            name='test_level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='testschedule',
            name='test_type',
            field=models.CharField(choices=[('PRE', 'PRE TEST'), ('POT', 'POT TEST'), ('POOT', 'POOT TEST'), ('POST', 'POST TEST')], max_length=10),
        ),
        migrations.DeleteModel(
            name='StudentTestStats',
        ),
        migrations.AddField(
            model_name='teststudeentstats',
            name='test_sched',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.testschedule'),
        ),
    ]
