# Generated by Django 3.1.3 on 2021-01-06 18:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0026_auto_20210106_2334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestStudeentStats',
            new_name='TestStudentStats',
        ),
    ]
