# Generated by Django 3.1.3 on 2021-01-06 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0027_auto_20210106_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTestStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datenow', models.DateTimeField(auto_now_add=True)),
                ('timegap', models.CharField(default='-', max_length=2)),
                ('times', models.CharField(default='-', max_length=2)),
                ('condectedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.studentenroll')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.testschedule')),
            ],
        ),
        migrations.DeleteModel(
            name='TestStudentStats',
        ),
    ]
