# Generated by Django 3.1.3 on 2021-01-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0028_auto_20210106_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentteststats',
            old_name='condectedBy',
            new_name='conductedBy',
        ),
    ]
