# Generated by Django 3.1.3 on 2021-01-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0029_auto_20210106_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentteststats',
            name='schedule',
        ),
        migrations.AddField(
            model_name='studentteststats',
            name='level',
            field=models.CharField(default='SUNN', max_length=20),
        ),
        migrations.AddField(
            model_name='studentteststats',
            name='status',
            field=models.CharField(default='6', max_length=1),
        ),
        migrations.AddField(
            model_name='studentteststats',
            name='subject',
            field=models.CharField(default='Telugu', max_length=20),
        ),
        migrations.AddField(
            model_name='studentteststats',
            name='testtype',
            field=models.CharField(choices=[('PRE', 'PRE TEST'), ('POT', 'POT TEST'), ('POOT', 'POOT TEST'), ('POST', 'POST TEST')], default='PRE', max_length=10),
        ),
    ]
