# Generated by Django 3.1.3 on 2021-01-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0030_auto_20210107_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentteststats',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
