# Generated by Django 3.1.3 on 2021-01-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0031_auto_20210107_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteststats',
            name='action',
            field=models.CharField(default='---', max_length=40),
        ),
    ]
