# Generated by Django 3.1.3 on 2021-01-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0032_studentteststats_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='testschedule',
            name='test_nickname',
            field=models.CharField(default='l0', max_length=5),
        ),
    ]
