# Generated by Django 3.1.3 on 2021-01-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0034_auto_20210108_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmarks',
            name='l11',
            field=models.IntegerField(default=-1),
        ),
    ]
