# Generated by Django 3.1.3 on 2021-01-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0039_auto_20210108_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentteststats',
            name='testtype',
            field=models.CharField(choices=[('PRE', 'PRE'), ('POT', 'POT'), ('POOT', 'POOT'), ('POST', 'POST')], default='PRE', max_length=10),
        ),
    ]
