# Generated by Django 3.1.3 on 2021-01-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0041_auto_20210108_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenroll',
            name='stuclass',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentteststats',
            name='testtype',
            field=models.CharField(default='PRE', max_length=10),
        ),
        migrations.AlterField(
            model_name='testschedule',
            name='test_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.telugulevels'),
        ),
        migrations.AlterField(
            model_name='testschedule',
            name='test_type',
            field=models.CharField(max_length=10),
        ),
    ]
