# Generated by Django 3.1.3 on 2021-01-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0043_auto_20210118_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmarks',
            name='POOT_g1',
            field=models.CharField(default=' ', max_length=2),
        ),
        migrations.AlterField(
            model_name='testmarks',
            name='POOT_g2',
            field=models.CharField(default=' ', max_length=2),
        ),
        migrations.AlterField(
            model_name='testmarks',
            name='POT_g6',
            field=models.CharField(default=' ', max_length=2),
        ),
    ]
